apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web-example
  name: g-started
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: web-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-example
    spec:
      containers:
      - image: aconchas/g-started
        name: g-started
        ports:
        - containerPort: 3000
