apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app.kubernetes.io/name: web-example
spec:
  containers:
    - name: web
      image: ubuntu
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
      args: [/bin/sh, -c,
              'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
      volumeMounts:
      - name: db
        mountPath: "/etc/db"
        readOnly: true
  volumes:
  - name: db
    secret:
      secretName: db-user-pass
      items:
      - key: username
        path: my-group/my-username
